version: '3'

services:
  database:
    image: mysql
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: company
      MYSQL_USER: pradeep
      MYSQL_PASSWORD: pradeep
    ports:
      - 3306:3306
    volumes:
     - dockerAngularSpringDatabaseData:/var/lib/mysql
    networks:
     - backendNetwork

  spring-boot-ems:
    image: openjdk:10-jre-slim
    container_name: spring-boot-ems
    ports:
      - 8080:8080
    depends_on:
      - database
    volumes:
      - ./spring-boot-ems/target/spring-boot-ems-0.0.1-SNAPSHOT.jar:/application.jar
    command: ["java", "-jar", "application.jar"]
    networks:
      - backendNetwork
      - frontendNetwork

  angular:
    image: nginx:alpine
    container_name: angular
    ports:
      - 4200:80
    depends_on:
      - spring-boot-ems
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./angular/dist/angular/:/usr/share/nginx/html
    networks:
      - frontendNetwork


volumes:
  dockerAngularSpringDatabaseData:

networks:
  backendNetwork:
  frontendNetwork:
