version: '3.7'

services:
  mysql:
    platform: linux/x86_64
    image: mysql/mysql-server:5.7.28
    container_name: mysql
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command:
      #mysql5.7及以上 版本 默认连接方式 不是以密码形式连接 所以远程连接不方便 改为密码连接
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
      --sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO"
    ports:
      - 3306:3306
    volumes:
      - "${MYSQL_DIR}/data:/var/lib/mysql"           # 挂载数据目录
      - "${MYSQL_DIR}/config:/etc/mysql/conf.d"      # 挂载配置文件目录
      - ./MySQL:/docker-entrypoint-initdb.d
    # networks:
    #   - backendNetwork

  wsbookstore:
    image: openjdk:11.0.4
    container_name: wsbookstore
    ports:
      - "9200:8080"
    volumes:
      - ./java-bookstore/build/libs/onlinebookstore-0.0.1-SNAPSHOT.jar:/application.jar
    # command: [ "java", "-jar", "application.jar" ]
    command: [ "java", "-Dspring.profiles.active=docker", "-jar", "application.jar" ]
    # networks:
    #   - backendNetwork
    #   - frontendNetwork
    depends_on:
      - mysql

  angular:
    image: nginx:alpine
    container_name: angular
    ports:
      - 4200:80
    depends_on:
      - wsbookstore
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      # - ./angular/dist/angular/:/usr/share/nginx/html
      - ./angular-bookstore/dist/angular-bookstore:/usr/share/nginx/html
    # networks:
    #   - frontendNetwork


# volumes:
#   dockerAngularSpringDatabaseData:

# networks:
#   backendNetwork:
#   frontendNetwork:
