spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql/springbootapps?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
file:
  path: /users/yantao/uploadPath/file/
